//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scentasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomOrderScent
    {
        public Nullable<int> ScentId { get; set; }
        public Nullable<int> CustomOrderId { get; set; }
        public int Id { get; set; }
    
        public virtual CustomOrder CustomOrder { get; set; }
        public virtual Scent Scent { get; set; }
    }
}
