//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scentasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomOrder()
        {
            this.CustomOrderScents = new HashSet<CustomOrderScent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string BottleSize { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomOrderScent> CustomOrderScents { get; set; }
    }
}
